# /zabbix_sample/roles/sh/tasks

- name: "add epel repository"
  yum_repository: name=epel description=epel baseurl="{{ epel_repo }}" gpgkey="{{ epel_key }}" gpgcheck={{ gpgcheck }} enabled=no

# スクリプト実行に必要なパッケージ
- name: "install the latest version of usbutils, alsa-lib-devel, alsa-utils, sox, rsh, telnet, ftp"
  yum: name={{ packages }} state=latest enablerepo=epel
  vars:
    packages:
      - usbutils
      - alsa-lib-devel
      - alsa-utils
      - sox
      - rsh
      - telnet
      - ftp

# スクリプトをインストール
- name: "put {{ alert.sh }}"
  template: src=alertsender.sh.j2 dest="{{ alert.sh }}"

- name: "add mode the {{ alert.sh }} file executable"
  file: path={{ alert.sh }} mode="ugo+x"